jobs:
  build_and_test:
  name: ci-golang-workflow
  on: [push]
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.15
        - run: go test
        - run: go run math.go