name: ci-go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go