name: ci0golang-workflow
on: [push]
jobs:
  chack-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.15
        - run: go test
        - run: go run math.go